//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstTask.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstTask.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись не была востановленна!.
        /// </summary>
        public static string ActivateFailed {
            get {
                return ResourceManager.GetString("ActivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись была успешно востановленна!.
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление прошло успешно!.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст сотрудника должен быть больше 18 лет!.
        /// </summary>
        public static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановить.
        /// </summary>
        public static string ButtonActivate {
            get {
                return ResourceManager.GetString("ButtonActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string ButtonAgainst {
            get {
                return ResourceManager.GetString("ButtonAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string ButtonCancellation {
            get {
                return ResourceManager.GetString("ButtonCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string ButtonToday {
            get {
                return ResourceManager.GetString("ButtonToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных организации.
        /// </summary>
        public static string CompanyEditFormHeader {
            get {
                return ResourceManager.GetString("CompanyEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой организации.
        /// </summary>
        public static string CompanyInsertFormHeader {
            get {
                return ResourceManager.GetString("CompanyInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название компании должно состоять из более чем 6 символов!.
        /// </summary>
        public static string CompnayNameLength {
            get {
                return ResourceManager.GetString("CompnayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка внесения изменений в базу данных!.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала не может быть больше сегодняшней!.
        /// </summary>
        public static string DateOfBeginNonCorrect {
            get {
                return ResourceManager.GetString("DateOfBeginNonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление прошло успешно!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить запись?.
        /// </summary>
        public static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление данных прошло успешно!.
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных сотрудника.
        /// </summary>
        public static string EmployeeEditFormHeader {
            get {
                return ResourceManager.GetString("EmployeeEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление сотрудника организации.
        /// </summary>
        public static string EmployeeFormHeader {
            get {
                return ResourceManager.GetString("EmployeeFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя сотрудника должно содержать более 10 символов!.
        /// </summary>
        public static string EmployeeNameLength {
            get {
                return ResourceManager.GetString("EmployeeNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация:.
        /// </summary>
        public static string FilterCompany {
            get {
                return ResourceManager.GetString("FilterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string FilterFullName {
            get {
                return ResourceManager.GetString("FilterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        public static string FilterName {
            get {
                return ResourceManager.GetString("FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга:.
        /// </summary>
        public static string FilterService {
            get {
                return ResourceManager.GetString("FilterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать по:.
        /// </summary>
        public static string FilterSorting {
            get {
                return ResourceManager.GetString("FilterSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус:.
        /// </summary>
        public static string FilterStatus {
            get {
                return ResourceManager.GetString("FilterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат БИН!.
        /// </summary>
        public static string FormatBIN {
            get {
                return ResourceManager.GetString("FormatBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправельный формат некоторых данных! (Телефон/ИИН/БИН/Код).
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат ИИН!.
        /// </summary>
        public static string FormatIIN {
            get {
                return ResourceManager.GetString("FormatIIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный формат номера телефона!.
        /// </summary>
        public static string FormatPhone {
            get {
                return ResourceManager.GetString("FormatPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат кода услуги должен быть: &quot;x11.111.111&quot;.
        /// </summary>
        public static string FormatServiceCode {
            get {
                return ResourceManager.GetString("FormatServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните корректно все поля!.
        /// </summary>
        public static string FormError {
            get {
                return ResourceManager.GetString("FormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр организаций.
        /// </summary>
        public static string HeadingCompanies {
            get {
                return ResourceManager.GetString("HeadingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация и ведение сотрудников организации.
        /// </summary>
        public static string HeadingEmployee {
            get {
                return ResourceManager.GetString("HeadingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр услуг.
        /// </summary>
        public static string HeadingServices {
            get {
                return ResourceManager.GetString("HeadingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оказанные услуги.
        /// </summary>
        public static string HeadingServicesHistory {
            get {
                return ResourceManager.GetString("HeadingServicesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр услуг оказываемых организацией.
        /// </summary>
        public static string HeadingServicesProvided {
            get {
                return ResourceManager.GetString("HeadingServicesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все поля формы являются обязательными!.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БИН.
        /// </summary>
        public static string LabelBIN {
            get {
                return ResourceManager.GetString("LabelBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string LabelBirthdayDate {
            get {
                return ResourceManager.GetString("LabelBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код услуги.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация.
        /// </summary>
        public static string LabelCompany {
            get {
                return ResourceManager.GetString("LabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала работы.
        /// </summary>
        public static string LabelDateOfBegin {
            get {
                return ResourceManager.GetString("LabelDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        public static string LabelEmployee {
            get {
                return ResourceManager.GetString("LabelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя.
        /// </summary>
        public static string LabelFullName {
            get {
                return ResourceManager.GetString("LabelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИИН.
        /// </summary>
        public static string LabelPersonalNumber {
            get {
                return ResourceManager.GetString("LabelPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период отчетности с .
        /// </summary>
        public static string LabelReportPeriod {
            get {
                return ResourceManager.GetString("LabelReportPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга.
        /// </summary>
        public static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат отчета.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите БИН.
        /// </summary>
        public static string PlaceholderBIN {
            get {
                return ResourceManager.GetString("PlaceholderBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату рождения.
        /// </summary>
        public static string PlaceholderBirthdayDate {
            get {
                return ResourceManager.GetString("PlaceholderBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите компанию.
        /// </summary>
        public static string PlaceholderCompany {
            get {
                return ResourceManager.GetString("PlaceholderCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату начала работы.
        /// </summary>
        public static string PlaceholderDateOfBegin {
            get {
                return ResourceManager.GetString("PlaceholderDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите сотрудника организации.
        /// </summary>
        public static string PlaceholderEmployee {
            get {
                return ResourceManager.GetString("PlaceholderEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string PlaceholderFullName {
            get {
                return ResourceManager.GetString("PlaceholderFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите полное имя.
        /// </summary>
        public static string PlaceholderPersonalNumber {
            get {
                return ResourceManager.GetString("PlaceholderPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите номер телефона.
        /// </summary>
        public static string PlaceholderPhone {
            get {
                return ResourceManager.GetString("PlaceholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите стоимость .
        /// </summary>
        public static string PlaceholderPrice {
            get {
                return ResourceManager.GetString("PlaceholderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите услугу.
        /// </summary>
        public static string PlaceholderService {
            get {
                return ResourceManager.GetString("PlaceholderService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите код.
        /// </summary>
        public static string PlaceholderServiceCode {
            get {
                return ResourceManager.GetString("PlaceholderServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение отчета.
        /// </summary>
        public static string ReportFormHeader {
            get {
                return ResourceManager.GetString("ReportFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение расписания.
        /// </summary>
        public static string SchedulerFormHeader {
            get {
                return ResourceManager.GetString("SchedulerFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных услуги.
        /// </summary>
        public static string ServiceEditFormHeader {
            get {
                return ResourceManager.GetString("ServiceEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой услуги.
        /// </summary>
        public static string ServiceInsertFormHeader {
            get {
                return ResourceManager.GetString("ServiceInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название услуги должно содержать более 6 символов!.
        /// </summary>
        public static string ServiceNameLength {
            get {
                return ResourceManager.GetString("ServiceNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных оказываемой услуги.
        /// </summary>
        public static string ServiceProvidedEditFormHeader {
            get {
                return ResourceManager.GetString("ServiceProvidedEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление оказываемой услуги.
        /// </summary>
        public static string ServiceProvidedInsertFormHeader {
            get {
                return ResourceManager.GetString("ServiceProvidedInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате рождения.
        /// </summary>
        public static string SortingByBirthdayDate {
            get {
                return ResourceManager.GetString("SortingByBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате начала работы.
        /// </summary>
        public static string SortingByDateOfBegin {
            get {
                return ResourceManager.GetString("SortingByDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По имени.
        /// </summary>
        public static string SortingByFullName {
            get {
                return ResourceManager.GetString("SortingByFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По названию.
        /// </summary>
        public static string SortingByName {
            get {
                return ResourceManager.GetString("SortingByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По убиыванию цены.
        /// </summary>
        public static string SortingByPriceDown {
            get {
                return ResourceManager.GetString("SortingByPriceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По возрастанию цены.
        /// </summary>
        public static string SortingByPriceUp {
            get {
                return ResourceManager.GetString("SortingByPriceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активно.
        /// </summary>
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалено.
        /// </summary>
        public static string StatusDisable {
            get {
                return ResourceManager.GetString("StatusDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга/Организация/Сотрудник не выбраны!.
        /// </summary>
        public static string ValidationComboBox {
            get {
                return ResourceManager.GetString("ValidationComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата не может быть больше действующей!.
        /// </summary>
        public static string ValidationMessageDateNonCorrect {
            get {
                return ResourceManager.GetString("ValidationMessageDateNonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите данные в формате:.
        /// </summary>
        public static string ValidationMessageFormatError {
            get {
                return ResourceManager.GetString("ValidationMessageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это поле является обязательным!.
        /// </summary>
        public static string ValidationMessageInputRequired {
            get {
                return ResourceManager.GetString("ValidationMessageInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно содержать минимальное количество симолов:.
        /// </summary>
        public static string ValidationMessageMinLenght {
            get {
                return ResourceManager.GetString("ValidationMessageMinLenght", resourceCulture);
            }
        }
    }
}
