//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstTask.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class View {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal View() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstTask.Resources.View", typeof(View).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановить.
        /// </summary>
        internal static string ButtonActivate {
            get {
                return ResourceManager.GetString("ButtonActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string ButtonCancellation {
            get {
                return ResourceManager.GetString("ButtonCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        internal static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        internal static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        internal static string ButtonToday {
            get {
                return ResourceManager.GetString("ButtonToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных организации.
        /// </summary>
        internal static string CompanyEditFormHeader {
            get {
                return ResourceManager.GetString("CompanyEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой организации.
        /// </summary>
        internal static string CompanyInsertFormHeader {
            get {
                return ResourceManager.GetString("CompanyInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить запись?.
        /// </summary>
        internal static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных сотрудника.
        /// </summary>
        internal static string EmployeeEditFormHeader {
            get {
                return ResourceManager.GetString("EmployeeEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление сотрудника организации.
        /// </summary>
        internal static string EmployeeFormHeader {
            get {
                return ResourceManager.GetString("EmployeeFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация:.
        /// </summary>
        internal static string FilterCompany {
            get {
                return ResourceManager.GetString("FilterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        internal static string FilterFullName {
            get {
                return ResourceManager.GetString("FilterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        internal static string FilterName {
            get {
                return ResourceManager.GetString("FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга:.
        /// </summary>
        internal static string FilterService {
            get {
                return ResourceManager.GetString("FilterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать по:.
        /// </summary>
        internal static string FilterSorting {
            get {
                return ResourceManager.GetString("FilterSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус:.
        /// </summary>
        internal static string FilterStatus {
            get {
                return ResourceManager.GetString("FilterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр организаций.
        /// </summary>
        internal static string HeadingCompanies {
            get {
                return ResourceManager.GetString("HeadingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация и ведение сотрудников организации.
        /// </summary>
        internal static string HeadingEmployee {
            get {
                return ResourceManager.GetString("HeadingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр услуг.
        /// </summary>
        internal static string HeadingServices {
            get {
                return ResourceManager.GetString("HeadingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оказанные услуги.
        /// </summary>
        internal static string HeadingServicesHistory {
            get {
                return ResourceManager.GetString("HeadingServicesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр услуг оказываемых организацией.
        /// </summary>
        internal static string HeadingServicesProvided {
            get {
                return ResourceManager.GetString("HeadingServicesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БИН.
        /// </summary>
        internal static string LabelBIN {
            get {
                return ResourceManager.GetString("LabelBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        internal static string LabelBirthdayDate {
            get {
                return ResourceManager.GetString("LabelBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код услуги.
        /// </summary>
        internal static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация.
        /// </summary>
        internal static string LabelCompany {
            get {
                return ResourceManager.GetString("LabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала работы.
        /// </summary>
        internal static string LabelDateOfBegin {
            get {
                return ResourceManager.GetString("LabelDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        internal static string LabelEmployee {
            get {
                return ResourceManager.GetString("LabelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя.
        /// </summary>
        internal static string LabelFullName {
            get {
                return ResourceManager.GetString("LabelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИИН.
        /// </summary>
        internal static string LabelPersonalNumber {
            get {
                return ResourceManager.GetString("LabelPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период отчетности с .
        /// </summary>
        internal static string LabelReportPeriod {
            get {
                return ResourceManager.GetString("LabelReportPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга.
        /// </summary>
        internal static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат отчета.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите БИН.
        /// </summary>
        internal static string PlaceholderBIN {
            get {
                return ResourceManager.GetString("PlaceholderBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату рождения.
        /// </summary>
        internal static string PlaceholderBirthdayDate {
            get {
                return ResourceManager.GetString("PlaceholderBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите компанию.
        /// </summary>
        internal static string PlaceholderCompany {
            get {
                return ResourceManager.GetString("PlaceholderCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату начала работы.
        /// </summary>
        internal static string PlaceholderDateOfBegin {
            get {
                return ResourceManager.GetString("PlaceholderDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите сотрудника организации.
        /// </summary>
        internal static string PlaceholderEmployee {
            get {
                return ResourceManager.GetString("PlaceholderEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        internal static string PlaceholderFullName {
            get {
                return ResourceManager.GetString("PlaceholderFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите полное имя.
        /// </summary>
        internal static string PlaceholderPersonalNumber {
            get {
                return ResourceManager.GetString("PlaceholderPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите номер телефона.
        /// </summary>
        internal static string PlaceholderPhone {
            get {
                return ResourceManager.GetString("PlaceholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите услугу.
        /// </summary>
        internal static string PlaceholderService {
            get {
                return ResourceManager.GetString("PlaceholderService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение отчета.
        /// </summary>
        internal static string ReportFormHeader {
            get {
                return ResourceManager.GetString("ReportFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение расписания.
        /// </summary>
        internal static string SchedulerFormHeader {
            get {
                return ResourceManager.GetString("SchedulerFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных услуги.
        /// </summary>
        internal static string ServiceEditFormHeader {
            get {
                return ResourceManager.GetString("ServiceEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой услуги.
        /// </summary>
        internal static string ServiceInsertFormHeader {
            get {
                return ResourceManager.GetString("ServiceInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование данных оказываемой услуги.
        /// </summary>
        internal static string ServiceProvidedEditFormHeader {
            get {
                return ResourceManager.GetString("ServiceProvidedEditFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление оказываемой услуги.
        /// </summary>
        internal static string ServiceProvidedInsertFormHeader {
            get {
                return ResourceManager.GetString("ServiceProvidedInsertFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате рождения.
        /// </summary>
        internal static string SortingByBirthdayDate {
            get {
                return ResourceManager.GetString("SortingByBirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате начала работы.
        /// </summary>
        internal static string SortingByDateOfBegin {
            get {
                return ResourceManager.GetString("SortingByDateOfBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По имени.
        /// </summary>
        internal static string SortingByFullName {
            get {
                return ResourceManager.GetString("SortingByFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По названию.
        /// </summary>
        internal static string SortingByName {
            get {
                return ResourceManager.GetString("SortingByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По убиыванию цены.
        /// </summary>
        internal static string SortingByPriceDown {
            get {
                return ResourceManager.GetString("SortingByPriceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По возрастанию цены.
        /// </summary>
        internal static string SortingByPriceUp {
            get {
                return ResourceManager.GetString("SortingByPriceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активно.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалено.
        /// </summary>
        internal static string StatusDisable {
            get {
                return ResourceManager.GetString("StatusDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга/Организация/Сотрудник не выбраны!.
        /// </summary>
        internal static string ValidationComboBox {
            get {
                return ResourceManager.GetString("ValidationComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата не может быть больше действующей!.
        /// </summary>
        internal static string ValidationMessageDateNonCorrect {
            get {
                return ResourceManager.GetString("ValidationMessageDateNonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите данные в формате:.
        /// </summary>
        internal static string ValidationMessageFormatError {
            get {
                return ResourceManager.GetString("ValidationMessageFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это поле является обязательным!.
        /// </summary>
        internal static string ValidationMessageInputRequired {
            get {
                return ResourceManager.GetString("ValidationMessageInputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно содержать минимальное количество симолов:.
        /// </summary>
        internal static string ValidationMessageMinLenght {
            get {
                return ResourceManager.GetString("ValidationMessageMinLenght", resourceCulture);
            }
        }
    }
}
